### ISSUE TITLE
missing Ubuntu Linux - bloop_0.5.3_amd64.deb  Release File

### ISSUE THREAD

**Issue by DharmSonariya** [BloopAI/bloop#1003]
Description:
I attempted to download the bloop_0.5.3_amd64.deb release for Ubuntu Linux from the [v0.5.3 release page](https://github.com/BloopAI/bloop/releases/tag/v0.5.3). However, when I clicked on the [link](https://github.com/BloopAI/bloop/releases/download/v0.5.3/bloop_0.5.3_amd64.deb), I received a 404 error, indicating the file is missing.

Steps to Reproduce:

Navigate to the [v0.5.3 release page](https://github.com/BloopAI/bloop/releases/tag/v0.5.3).
Click on the bloop_0.5.3_amd64.deb link to download the file.
Observe the 404 error.
Expected Behavior:
The bloop_0.5.3_amd64.deb file should be available for download.

Actual Behavior:
Received a 404 error, indicating the file is not present.

**Comment by anastasiya1155** [comment]
Sorry, @DharmSonariya have just uploaded, please check again
