### ISSUE TITLE
feature(studio): jump between ranges

### ISSUE THREAD

**Issue by llllvvuu** [BloopAI/bloop#1028]
**What's the problem?**
Let's say I have a big file, and 10 ranges within that file are imported into Code Studio. Maybe I'm missing something but I can't figure out how to move between the ranges.

**What's the solution?**
A few options:
- Up/down buttons
- Keyboard shortcut, e.g. `]r` and `[r`
- Minimap

**Comment by anastasiya1155** [comment]
This will be added in the next release
