### ISSUE TITLE
Mac doesn't work in bloop

### ISSUE THREAD

**Issue by Guanbin-Huang** [BloopAI/bloop#1051]
Device Information:

MacBook Air 13" with M2 chip, 2022 model
Memory: 16 GB
Startup Disk: Macintosh HD
OS: macOS Sonoma 14.0

Software:
Application: Bloop
Version: 0.5.6 (aarch64)
Installation source: 
macOS 11+ (Apple Silicon) - [bloop_0.5.6_aarch64.dmg](https://github.com/BloopAI/bloop/releases/download/v0.5.6/bloop_0.5.6_aarch64.dmg)

Problem Description:
After downloading and clicking on the application, it gets stuck in a loading state and never progresses to the application interface.
<img width="966" alt="image" src="https://github.com/BloopAI/bloop/assets/30463291/d1b641e7-0e50-4062-b4fe-5bf4b0b48ec9">

**Comment by ggordonhall** [comment]
Can you post the contents of your latest `/logs` file? On Mac it's at `~/Library/Application\ Support/ai.bloop.bloop/bleep/logs`.

**Comment by Guanbin-Huang** [comment]
there's nothing.
<img width="707" alt="image" src="https://github.com/BloopAI/bloop/assets/30463291/401c1dbb-ebc5-4362-ad8e-20ebdcb93eb9">

**Comment by ggordonhall** [comment]
Do you have any processes running on ports `7878`, `6333` or `6334`?

**Comment by Guanbin-Huang** [comment]
<img width="701" alt="image" src="https://github.com/BloopAI/bloop/assets/30463291/6a837acb-8998-4b4f-98da-e7586eded4c5">

**Comment by Guanbin-Huang** [comment]
I was able to use it a few weeks ago, but for some reason, I can't use it now.

**Comment by Guanbin-Huang** [comment]
the issue i came across looks very similar with this one.

https://github.com/BloopAI/bloop/issues/1035#issue-1935494321

**Comment by ggordonhall** [comment]
Yes, this is likely the same issue. I'll close this thread, and we'll continue the discussion on #1035.
