### ISSUE TITLE
[Feature Request] List the previous sessions of chats with histories inspectable for referencing and in case of crash

### ISSUE THREAD

**Issue by nekomeowww** [BloopAI/bloop#1085]
## What's the problem?

Currently the implementation of Bloop.ai doesn't provide me a way to select a previous session of chat to continue, or any chat histories to be referenced with. This is quite annoying when

1. reboot needed OS update take place
2. application suddenly crashed unexpectedly
3. restart application when encountered bugs since usually restart is a kind of strategy to fix bugs from end user

Beyond chat histories, logging inspect ability is useful when I encountered some bugs and me as being a developer could help and diagnostic.

## What's the solution?

- Provide a list of previous sessions of chats with histories inspectable for users to choose.
  - A list of sessions
  - When user has chosen one of the sessions, include all the chat histories in chat window
  - Ability to continue chat with the previous contexts
 
## Additional context

None.

**Comment by ggordonhall** [comment]
bloop stores previous conversations in an SQLiteDB, which should persist when the application restarts. Have you found that they're wiped when you re-open the app? Which OS are you using?

**Comment by ggordonhall** [comment]
Did you [manually delete your index directory](https://github.com/BloopAI/bloop/tree/main/apps/desktop#wiping-an-index)? Doing this will also wipe your conversation history.

**Comment by nekomeowww** [comment]
Nope. But I have tried to removed an existing indexed repository, while I have total of three repository before the removeal.

**Comment by nekomeowww** [comment]
Should I change the title to `[Bug]` since listing and data persistence is expected? 

BTW, I have joined the Discord server, if further diagnostic and debugging is required, we   could do it in Discord server for better and faster conversation speed.

**Comment by ggordonhall** [comment]
Conversations are tied to repositories, so if you remove a repo you won't be able to view your conversations associated with it. If you remove then re-index a repo, your conversations should persist (accessible via this button):

<img width="194" alt="Screenshot 2023-10-26 at 10 47 59" src="https://github.com/BloopAI/bloop/assets/24595376/f3e53c7a-654b-411c-a2d2-edb26189355e">

**Comment by nekomeowww** [comment]
Ah, I see. This button is not so obvious for me to find. I find my conversations now.

And is it possible to list all the previous chatted conversations on Home page?

**Comment by ggordonhall** [comment]
Currently it's not possible: you have to navigate to a repo to see the previous conversations. This is good feedback though. We'll take this into consideration when we're updating the UX here.

**Comment by nekomeowww** [comment]
Glad to hear that! Looking forward to see the upcoming updated UI/UX.

Should I close this issue?
