### ISSUE TITLE
[Feature Request] Logs to be able to inspect and diagnose from

### ISSUE THREAD

**Issue by nekomeowww** [BloopAI/bloop#1086]
## What's the problem?

As #1085 stated: logging inspect ability is useful when I encountered some bugs and me as being a developer could help and diagnostic. I've encountered several bugs when try to use it:

1. Indexing and processing stucked
2. Failed to send chat messages with GPT (possibly failed to send requests?)

And I have no ways to find out what is wrong, am I missing something or network breaks, therefor bug report involves with such ability.

## What's the solution?

- Provide a way to diagnostic, or view logs when user has the ability to do
  - diagnostic tool to generate from when reporting bugs
  - log inspect tools for users, or physical log files to be find with guides in documentations
  - maybe devtools or similar tools for users to interact with when encountered network issues, frontend bugs

## Additional context 

None.

**Comment by ggordonhall** [comment]
Hi @nekomeowww, bloop writes logs from `bleep` (the server) to disk. Depending on your OS you can find them at:
- `~/Library/Application\ Support/ai.bloop.bloop/bleep/logs`
- `%APPDATA%/bloop/bleep/logs`
- `~/.local/share/bloop/bleep/logs`

Agree that we can make this more prominent in the documentation.

**Comment by nekomeowww** [comment]
Nicely. Can I do something for the documentation as contribution?
