### ISSUE TITLE
[Feature Request] Multiple chats with customizable chat titles instead of same title for multiple tabs for the same repository

### ISSUE THREAD

**Issue by nekomeowww** [BloopAI/bloop#1087]
## What's the problem?

It's a bit annoying when started multiple chats with GPT for the same repository. Navigation is frustrating when you need find and switch off all the tabs with the same title, should be able to at least rename the tabs for users who started multiple chats with the same repository. As #1085 stated, the ability to have histories of chats is crucial, therefore having the ability to rename or auto generate titles for multiple chats and make these titles persistent is needed too.

## What's the solution?

- Ability to rename tabs.
- Or group chats for the same repository under the same tab, and allow users to organize multiple chats on the left sidebar, just like what [poe.com](poe.com) and [chat.openai.com](chat.openai.com) does.
- The state of the renamed title persisted, will be listed for previous sessions

## Additional context

None.

**Comment by anastasiya1155** [comment]
Hey @nekomeowww thanks for your suggestion. In fact, we're already planning a big design change to the app that will solve this issue together with a couple of others.

**Comment by nekomeowww** [comment]
Ok. Sure.

Then should this issue be closed since it's planned? Or should we keep it until the new big design change updated?
