### ISSUE TITLE
GPT4 backend?

### ISSUE THREAD

**Issue by leiwen83** [BloopAI/bloop#1094]
Hi,

As current the backend source code is missing in this repo, app built directly from source is not functional...

So may I ask when the backend server could be release? So that we may use our own gpt or other open source LLM?

Thx~

**Comment by imotai** [comment]
Same requirement.

**Comment by imotai** [comment]
> Hi,
> 
> As current the backend source code is missing in this repo, app built directly from source is not functional...
> 
> So may I ask when the backend server could be release? So that we may use our own gpt or other open source LLM?
> 
> Thx~

I have some demo code to  support openai api in the bleep server

**Comment by ggordonhall** [comment]
@leiwen83 You can now build and run bloop from source with a custom OpenAI API key. Instructions for how to do so here: https://github.com/BloopAI/bloop?tab=readme-ov-file#building-from-source

The OpenAI API code is here: https://github.com/BloopAI/bloop/tree/oss/server/bleep/src/llm
