### ISSUE TITLE
Unable to use locally due to "Service panicked: auth not configured" errors

### ISSUE THREAD

**Issue by dpkirchner** [BloopAI/bloop#1150]
**Describe the bug**
I am unable to get past the "sign in" page when I run bloop code locally

**Expected behavior**
I expected to be able to get past the sign in page. I'm not sure what I should see after that, though.

**To Reproduce**

I'm running macOS Ventura 13.5.1 on an m1 max. I'm using a slightly old version of node/npm (v21.2.0, 10.2.3) and a recent rust (1.76.0, nightly). I followed these steps:

```
git clone https://github.com/BloopAI/bloop.git
cd bloop

# in one window

cargo run -p bleep --release --features=color-eyre -- --source-dir $(pwd)/..../path/to/code

# in another window

echo API_URL=http://localhost:7878/api > .env
npm install && npm run start-web

# and another window

docker run -p 6333:6333 -p 6334:6334 -v $(pwd)/Documents/qdrant:/qdrant/storage qdrant/qdrant
```

Then I visit http://localhost:5173/ and see an unexpected "Use GitHub to sign in to your account" prompt (aside: I'm running locally, ideally "offline", so I didn't expect to have to auth with anything). Further, the "Sign In With GitHub" button is disabled (verified with devtools).

When the frontend hits http://localhost:7878/api/studio the bleep server responds with `{"kind":"user","message":"didn't have user ID"}` and prints this on the command line:

```
2023-11-22T16:59:49.960994Z ERROR bleep: panic occurred: panicked at /.../Documents/git/bloop/server/bleep/src/webserver/github.rs:28:10:
auth not configured
The application panicked (crashed).
Message:  auth not configured
Location: /.../Documents/git/bloop/server/bleep/src/webserver/github.rs:28

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
2023-11-22T16:59:49.961131Z ERROR tower_http::catch_panic: Service panicked: auth not configured
2023-11-22T16:59:49.961157Z ERROR bleep: panic occurred: panicked at /.../Documents/git/bloop/server/bleep/src/webserver/github.rs:113:14:
auth not configured
The application panicked (crashed).
Message:  auth not configured
Location: /.../Documents/git/bloop/server/bleep/src/webserver/github.rs:113

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Additional context**

I'm on commit 97272d7dbe89e311a978e282ee9860246c9079cd.

This is my first time using the tool. I totally may have missed some documentation somewhere. I followed the steps here:

https://github.com/BloopAI/bloop/blob/main/client/README.md
https://github.com/BloopAI/bloop/tree/main/server

I skipped the "sync github" part because I don't want to connect to GitHub, I have all of my source cloned locally. (If it's absolutely necessary to set up a client id, I can do that; I'd suggest making the `--github-client-id` flag mandatory if that's the case).

**Comment by ggordonhall** [comment]
It should be now possible to build and run bloop without hitting these errors. Check out the `oss` branch and follow the instructions here: https://github.com/BloopAI/bloop?tab=readme-ov-file#building-from-source
