### ISSUE TITLE
Bloop does not work after upgrading to new version

### ISSUE THREAD

**Issue by cc15522** [BloopAI/bloop#1182]
**Describe the bug**
I upgraded to the new version of Bloop, however, the software now crashes or freezes when trying to open it. I tried to down grade to the version I was originally using but the issue continues to occur.

**To Reproduce**

This is my system

Type: Darwin
Platform: darwin
Arch: aarch64
Version: 13.5.1

I upgraded to Bloop to the following version 

Version 0.5.11 (20231215.161637)

**Comment by ggordonhall** [comment]
Hey @cc15522, thanks for opening this.

Looks like this is a `Too many files open (OS error 24)` error in Qdrant. https://github.com/BloopAI/bloop/pull/1181 should address this, I'll create a bloop build that you can test.

**Comment by SamuelScc** [comment]
try to delete the index file in MacOS System，| MacOS      | `~/Library/Application\ Support/ai.bloop.bloop， and then restart bloop，you can try this way @cc15522  @ggordonhall

**Comment by cc15522** [comment]
I deleted the bloop.ai application then deleted the entire ~/Library/Application Support/ai.bloop.bloop folder, then reinstalled version 5.11. Of course, all repositories that I had previously indexed are now gone. But it now works.

**Comment by ggordonhall** [comment]
@cc15522 Have you been able to reproduce this on v0.5.12?
