### ISSUE TITLE
V0.5.12 All corner characters are automatically repeated when entering

### ISSUE THREAD

**Issue by OnlyAIGC** [BloopAI/bloop#1194]
**Describe the bug**
In the state of Chinese input method, that is, in the state of full Angle symbol, the comma and period of the full Angle will be repeated.

**Expected behavior**
Use Chinese prompt words in the dialog box
**To Reproduce**
How can we reproduce the bug? Helpful information could include:
- WIN11
- When the chat is not started, the input field automatically repeats the full corner character when typing

**Screenshots or output**
![bloop bug_20231223_194815](https://github.com/BloopAI/bloop/assets/105823680/c3646fa9-0c1f-4a53-9ed3-426f68fa5af1)

**Additional context**
version V0.5.12

**Comment by anastasiya1155** [comment]
Hey @OnlyAIGC , thank you for the bug report! I am trying to reproduce it now but with no luck for now. What type of input do you use? I tried Wubi, Pinyin, and Shuangpin. All behaving normally.

**Comment by fishpigbird** [comment]
![2024-1-13-14-28-21](https://github.com/BloopAI/bloop/assets/128216091/5e65b624-d9e4-4d95-b405-af162cc9eca1)
![image](https://github.com/BloopAI/bloop/assets/128216091/8122aebc-c167-4ea0-9820-8cb9b747f630)
![image](https://github.com/BloopAI/bloop/assets/128216091/46448641-e6b8-4610-9ca0-f86b923d7fbd)

**Comment by anastasiya1155** [comment]
Thank you, I was able to reproduce it on a Windows machine. It seems like the issue is in one of the libraries we use for this input. We will investigate it further

**Comment by OnlyAIGC** [comment]
> Thank you, I was able to reproduce it on a Windows machine. It seems like the issue is in one of the libraries we use for this input. We will investigate it further谢谢，我能够在 Windows 机器上重现它。问题似乎出在我们用于此输入的库之一中。我们将进一步调查此事

Thanks for the official attention, there is another issue that I'm not sure counts as a problem. I've found that the number of characters that can be entered in v0.5.12 is much less than in v0.5.10, and the limit is triggered very quickly. I was able to find this out because I often need to paste in snippets of code.

**Comment by anastasiya1155** [comment]
Hey @OnlyAIGC, this issue is just one of several others with the library we are using for the chat input. We decided to provide another type of input for users struggling with the current one. Please try our latest release https://github.com/BloopAI/bloop/releases/tag/v0.6.2, it has an alternative input type alongside other new features and bug fixes. You can choose a type of input in Settings -> Preferences. Would love to hear your feedback on it!

**Comment by OnlyAIGC** [comment]
> Hey @OnlyAIGC, this issue is just one of several others with the library we are using for the chat input. We decided to provide another type of input for users struggling with the current one. Please try our latest release https://github.com/BloopAI/bloop/releases/tag/v0.6.2, it has an alternative input type alongside other new features and bug fixes. You can choose a type of input in Settings -> Preferences. Would love to hear your feedback on it!

**Comment by OnlyAIGC** [comment]
> Hey @OnlyAIGC, this issue is just one of several others with the library we are using for the chat input. We decided to provide another type of input for users struggling with the current one. Please try our latest release https://github.com/BloopAI/bloop/releases/tag/v0.6.2, it has an alternative input type alongside other new features and bug fixes. You can choose a type of input in Settings -> Preferences. Would love to hear your feedback on it!

ok，Thanks ！
