### ISSUE TITLE
When I typed the question into the dialog, the program crashed

### ISSUE THREAD

**Issue by 982945902** [BloopAI/bloop#1199]
**Describe the bug**
frontend

When I typed the question into the dialog, the program crashed
```
null is not an object (evaluating 'e.nodeType') Sft@tauri://localhost/assets/index-735f03ea.js:267:48809 F9t@tauri://localhost/assets/index-735f03ea.js:263:5063 Eft div rht@tauri://localhost/assets/index-735f03ea.js:273:1701 div div aht@tauri://localhost/assets/index-735f03ea.js:275:1928 form div lht@tauri://localhost/assets/index-735f03ea.js:275:4767 div Sre@tauri://localhost/assets/index-735f03ea.js:40:27714 div div Zpt@tauri://localhost/assets/index-735f03ea.js:294:5586 w9@tauri://localhost/assets/index-735f03ea.js:117:3810 errorBoundary(Zpt) edn@tauri://localhost/assets/index-735f03ea.js:429:3282 w9@tauri://localhost/assets/index-735f03ea.js:117:3810 errorBoundary(edn) @tauri://localhost/assets/index-735f03ea.js:117:93185 @tauri://localhost/assets/index-735f03ea.js:117:91507 @tauri://localhost/assets/index-735f03ea.js:117:90477 @tauri://localhost/assets/index-735f03ea.js:117:87257 @tauri://localhost/assets/index-735f03ea.js:117:92499 @tauri://localhost/assets/index-735f03ea.js:117:8333 div ndn@ @tauri://localhost/assets/index-735f03ea.js:452:63330 @tauri://localhost/assets/index-735f03ea.js:447:15662 @tauri://localhost/assets/index-735f03ea.js:429:6132 @tauri://localhost/assets/index-735f03ea.js:429:10489 Whn@tauri://localhost/assets/index-735f03ea.js:452:183286 w9@tauri://localhost/assets/index-735f03ea.js:117:3810 errorBoundary(Whn) Pve@tauri://localhost/assets/index-735f03ea.js:72:2172 Ive@tauri://localhost/assets/index-735f03ea.js:81:461 div aCn@tauri://localhost/assets/index-735f03ea.js:454:530

Type: Darwin
Platform: darwin
Arch: aarch64
Version: 13.0.0
```

**Expected behavior**
What did you expect to happen?

**To Reproduce**
How can we reproduce the bug? Helpful information could include:
- Details about your system
- The data that you had indexed
- The query that you ran

**Screenshots or output**
If applicable, add screenshots to help illustrate the bug.

**Additional context**

**Comment by anastasiya1155** [comment]
@982945902 Thank you for the bug report! I am trying to reproduce it but with no luck. Can you give more details about it? What language do you type in? If it's not English then what input type do you use (Pinyin, Kana, etc). Do you use anything besides a built-in keyboard to type? Does this error happen consistently, after some action? Thank you in advance!

**Comment by 982945902** [comment]
@anastasiya1155   I used the default Chinese input method of macos, and the interesting thing is that I can click Preset question, then clear it, and then type my question, which is how I use it now

**Comment by anastasiya1155** [comment]
@982945902 thank you, but I still can't reproduce it. I tried all input methods on the screenshot:
<img width="534" alt="Screenshot 2024-01-12 at 05 09 06" src="https://github.com/BloopAI/bloop/assets/35258279/4c56fd6a-8b13-445a-a62e-c55b15bd2751">
Are they different for you?

**Comment by 982945902** [comment]
@anastasiya1155  I  certained my local Pinyin cause crash, when i  using English also can't reproduce , maybe difference Pinyin version cause you can't reproduce it.   finally i think do not affect the usage， when i find reason will commit issue
