### ISSUE TITLE
Lack of sending messages

### ISSUE THREAD

**Issue by fishpigbird** [BloopAI/bloop#1202]
**Describe the bug**
Frequent occurrences.
When it happens, bloop gets a white screen logo then reloads
![2024-1-13-20-3-21](https://github.com/BloopAI/bloop/assets/128216091/c0cbb08a-267c-4ec9-b0ed-13e60ead8832)

**Comment by anastasiya1155** [comment]
Thank you for the bug report, it will be fixed in the next release
