### ISSUE TITLE
iss

### ISSUE THREAD

**Issue by zbl929** [BloopAI/bloop#1206]
Synchronizing the Github public repository does not synchronize all files, such as a total of three JSON files, and only one is synchronized.

**Comment by ggordonhall** [comment]
By default bloop does not index very large files. You can manually index them by pressing the 'index' button:

![Screenshot 2024-01-19 at 10 07 13](https://github.com/BloopAI/bloop/assets/24595376/0722eeff-218b-4b93-a6ae-589e58c55013)
