### ISSUE TITLE
support mac intel i7?

### ISSUE THREAD

**Issue by Robinbiao** [BloopAI/bloop#1225]
mac info:
MacBook Pro (16-inch, 2019);
2.6 GHz 六核Intel Core i7;
donot use soft
**Describe the bug**
A clear and concise description of what the bug is. If appropriate add a `frontend` or `backend` label.

**Expected behavior**
What did you expect to happen?

**To Reproduce**
How can we reproduce the bug? Helpful information could include:
- Details about your system
- The data that you had indexed
- The query that you ran

**Screenshots or output**
If applicable, add screenshots to help illustrate the bug.

**Additional context**

**Comment by Robinbiao** [comment]
Something bad happened

Type: Darwin
Platform: darwin
Arch: x86_64
Version: 12.1.0

**Comment by Robinbiao** [comment]
error info ：
null is not an object (evaluating 'e.nodeType') Sft@tauri://localhost/assets/index-735f03ea.js:267:1851546 F9t@tauri://localhost/assets/index-735f03ea.js:263:1757407 Eft div rht@tauri://localhost/assets/index-735f03ea.js:273:1865286 div div aht@tauri://localhost/assets/index-735f03ea.js:275:1867798 form div lht@tauri://localhost/assets/index-735f03ea.js:275:1870637 div Sre@tauri://localhost/assets/index-735f03ea.js:40:115023 div div Zpt@tauri://localhost/assets/index-735f03ea.js:294:1949738 w9@tauri://localhost/assets/index-735f03ea.js:117:544641 errorBoundary(Zpt) edn@tauri://localhost/assets/index-735f03ea.js:429:4097268 w9@tauri://localhost/assets/index-735f03ea.js:117:544641 errorBoundary(edn) @tauri://localhost/assets/index-735f03ea.js:117:634016 @tauri://localhost/assets/index-735f03ea.js:117:632338 @tauri://localhost/assets/index-735f03ea.js:117:631308 @tauri://localhost/assets/index-735f03ea.js:117:628088 @tauri://localhost/assets/index-735f03ea.js:117:633330 @tauri://localhost/assets/index-735f03ea.js:117:549164 div ndn@ @tauri://localhost/assets/index-735f03ea.js:452:4299487 @tauri://localhost/assets/index-735f03ea.js:447:4199086 @tauri://localhost/assets/index-735f03ea.js:429:4100118 @tauri://localhost/assets/index-735f03ea.js:429:4104475 Whn@tauri://localhost/assets/index-735f03ea.js:452:4419443 w9@tauri://localhost/assets/index-735f03ea.js:117:544641 errorBoundary(Whn) Pve@tauri://localhost/assets/index-735f03ea.js:72:286467 Ive@tauri://localhost/assets/index-735f03ea.js:81:287763 div aCn@tauri://localhost/assets/index-735f03ea.js:454:4611623

Type: Darwin
Platform: darwin
Arch: x86_64
Version: 12.1.0

**Comment by anastasiya1155** [comment]
@Robinbiao thank you for the bug report. Can you give us some more info:
- What input method are you using?
- Do you use any external hardware or software that influences your typing?
- Does this error happen when you type something specific? Can you give 1-2 examples?

**Comment by Robinbiao** [comment]
> @Robinbiao thank you for the bug report. Can you give us some more info:
> 
> * What input method are you using?
> * Do you use any external hardware or software that influences your typing?
> * Does this error happen when you type something specific? Can you give 1-2 examples?

1.  input method:  Sogou Wubi.
2. not use external hardware.
3. when input any content , alert this error

**Comment by anastasiya1155** [comment]
Hey @Robinbiao , we couldn't work around this issue as it is a bug in an underlying library, so instead we provide an alternative input that doesn't use this library. Please try our latest release https://github.com/BloopAI/bloop/releases/tag/v0.6.2 . You can choose a type of input in Settings -> Preferences. Would love to hear your feedback on it!
