### ISSUE TITLE
Crash on Launch for All Bloop Versions from 0.5.12 to 0.6.2 on Mac Mini M1

### ISSUE THREAD

**Issue by R3alloc** [BloopAI/bloop#1233]
I am experiencing an issue with my Mac Mini M1, 8GB, running macOS version 14.3.1 (23D60). I have attempted to run all versions of Bloop ranging from 0.5.12 to 0.6.2. However, each one crashes immediately upon startup. 

![image](https://github.com/BloopAI/bloop/assets/37363760/2c32cbb8-bd09-402b-bb51-6c43032759d3)

**Comment by anastasiya1155** [comment]
Hey @R3alloc thanks for reaching out. Can you try clearing your cache (~/Library/Application\ Support/ai.bloop.bloop) and restarting bloop?

**Comment by R3alloc** [comment]
cool! Clearing cache fix the problem. Thank you so much!
