### ISSUE TITLE
when run bleep container ,got error: docker run  --rm  bloop:test --qdrant-url=http://192.168.30.80:6334 Error: qdrant initialization failed  Caused by:     0: semantic error     1: Failed to create ONNX Runtime session: Load model from /model/model.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by JimLeeee** [BloopAI/bloop#1243]
build container using the Dockerfile
When try to start the container, got error:

docker run  --rm  bloop:test --qdrant-url=http://192.168.30.80:6334
Error: qdrant initialization failed

Caused by:
    0: semantic error
    1: Failed to create ONNX Runtime session: Load model from /model/model.onnx failed:Protobuf parsing failed.

**Comment by JimLeeee** [comment]
need to download the model file

**Comment by ccly1996** [comment]
> need to download the model file

hello,where to download the model
