### ISSUE TITLE
Why it need to read my repos? How to use it local repo only?

### ISSUE THREAD

**Issue by GF-Huang** [BloopAI/bloop#1248]
![image](https://github.com/BloopAI/bloop/assets/4510984/7803fc38-97ee-46a3-8945-199074d6e7cf)

**Comment by nanamikato** [comment]
how did you install it in windows, pls tell, im unable to do?

**Comment by GF-Huang** [comment]
> @GF-Huang how did you install it in windows, pls tell, im unable to do?

![image](https://github.com/BloopAI/bloop/assets/4510984/663c3673-2fdf-4c9c-a6f7-716765246778)

**Comment by nanamikato** [comment]
I see, got it. Even my chrome browser is recommending to not install it (can hack)

**Comment by GF-Huang** [comment]
> I see, got it. Even my chrome browser is recommending to not install it (can hack)

Browser not recommending is another issue, which because of an exe file from internet without digital signature is dangerous.

**Comment by keinsell** [comment]
> Browser not recommending is another issue, which because of an exe file from internet without digital signature is dangerous.

Gosh... This is modern day software developer community?

**Comment by ggordonhall** [comment]
You can now build and run bloop from source by directly providing your GitHub Access Token. See instructions here: https://github.com/BloopAI/bloop?tab=readme-ov-file#building-from-source
