### ISSUE TITLE
Remove updater from Local build instructions 

### ISSUE THREAD

**Issue by drewbitt** [BloopAI/bloop#1263]
## Problem

When building locally following the instructions in https://github.com/BloopAI/bloop/blob/oss/apps/desktop/README.md, you will get the following error. 

```
+ exit 0
    Bundling [tauri_bundler::bundle::updater_bundle] /Users/drewbitt/Repos/bloop/target/release/bundle/macos/bloop.app.tar.gz (/Users/drewbitt/Repos/bloop/target/release/bundle/macos/bloop.app.tar.gz)
    Finished [tauri_bundler::bundle] 2 bundles at:
        /Users/drewbitt/Repos/bloop/target/release/bundle/macos/bloop.app
        /Users/drewbitt/Repos/bloop/target/release/bundle/dmg/bloop_0.6.4_aarch64.dmg
        /Users/drewbitt/Repos/bloop/target/release/bundle/macos/bloop.app.tar.gz (updater)

       Error [tauri_cli_node] A public key has been found, but no private key. Make sure to set `TAURI_PRIVATE_KEY` environment variable.
 ```

### Info

This is because of https://github.com/BloopAI/bloop/blob/222a131cf9679cf933327904e06f1e0debc6e207/apps/desktop/src-tauri/tauri.conf.json#L94

### Screenshots
<img width="274" alt="43247" src="https://github.com/BloopAI/bloop/assets/26885897/a684aacc-2cb4-4b72-9214-21ffeafb29ef">

The updater being present will also prompt this, even though this is a local build and we should not be downloading remote updates of prebuilds. 

Also secondarily, it is giving me a prompt to update to 0.6.5, but I have the latest branch; this is because you pushed out a 0.6.5 but did not update several locations 
<img width="345" alt="63529" src="https://github.com/BloopAI/bloop/assets/26885897/460e8f71-576b-40d3-ba39-b46acdca19e6">

## Recommendation

Remove the updater code from local build instructions. We can't sign it with your private key and it's not useful.

**Comment by anastasiya1155** [comment]
Thank you, @drewbitt, for reporting this issue. I've submitted a pull request to address it. Feel free to test it locally to confirm if it resolves the problem on your end. Otherwise, it should be merged shortly.

**Comment by drewbitt** [comment]
That works!
