### ISSUE TITLE
Github authentication not working

### ISSUE THREAD

**Issue by cc15522** [BloopAI/bloop#1286]
**Describe the bug**
I opened the Bloop application on mac today and was required to authenticate my Github account. I did this, however, the link generated does not work. I have been using Bloop regularly for months now and this is the first time I have been asked to do this. As a result, I am now unable to use the Bloop App

This is the link generated

`https://production-github-oauth.auth.eu-west-1.amazoncognito.com/oauth2/authorize?response_type=code&scope=email+openid+profile&redirect_url=https%3A%2F%2Fauth.bloop.ai%2Fcomplete&client_id=6iso6185sujqtfttt1ik63sctc&state=48357e57-b864-4fbc-b8fb-5eacc610e07d`

The error returned is as follows 

`This site can’t be reachedCheck if there is a typo in production-github-oauth.auth.eu-west-1.amazoncognito.com.
DNS_PROBE_FINISHED_NXDOMAIN`

![Untitled](https://github.com/user-attachments/assets/2b0c2c07-520d-4e74-9f51-9200acefb0b7)

**Comment by shivamksharma** [comment]
I encountered a similar issue today while using the BloopAI Application and now unable to use the Bloop Application !

**Comment by dbsxdbsx** [comment]
Me too, win10, and I am sure there is no proxy VPN issue, since I can get to github with no stuck.

**Comment by nugaon** [comment]
Same issue here, the auth link does not work, I get error message:

`We can’t connect to the server at production-github-oauth.auth.eu-west-1.amazoncognito.com.`

**Comment by CBX001** [comment]
Having the same issue too!

**Comment by hcbaxiom** [comment]
Having same issue, windows 11

**Comment by banduoba** [comment]
Mee to,how to fix this bug.

**Comment by the6thexe** [comment]
Same problem, on Windows 11 everything worked the first time, but then this error

**Comment by ccly1996** [comment]
same problem

**Comment by banduoba** [comment]
When can this bug issue be fixed?

**Comment by stunningpixels** [comment]
Hi guys, we emailed everyone a few weeks ago - the OpenAI proxy we host has been shut down as we're focussing on mainframe modernisation. You can still use bloop open source with your own OpenAI keys.

**Comment by cc15522** [comment]
Hi @stunningpixels 

To use it with our OpenAI keys should we use these instructions or is there a different link to instructions?

https://github.com/BloopAI/bloop?tab=readme-ov-file#building-from-source


`the OpenAI proxy we host has been shut down as we're focussing on mainframe modernisation`

Will the service be available as usual at a time in the future?

**Comment by stunningpixels** [comment]
> Hi @stunningpixels
> 
> To use it with our OpenAI keys should we use these instructions or is there a different link to instructions?
> 
> https://github.com/BloopAI/bloop?tab=readme-ov-file#building-from-source
> 
> `the OpenAI proxy we host has been shut down as we're focussing on mainframe modernisation`
> 
> Will the service be available as usual at a time in the future?

That's correct, please follow these instructions for the open source version.

We don't intend to host a proxy in the future, unfortunately.
