### ISSUE TITLE
Discord invite URL missing in CONTRIBUTING.md

### ISSUE THREAD

**Issue by zawarudo** [BloopAI/bloop#205]
Could not find the discord invite listed in the [documentation](https://github.com/BloopAI/bloop/blob/main/CONTRIBUTING.md)
Currently points to `https://discord-invite-address/`

Also could not find it on your [site](https://bloop.ai/) or [twitter](https://twitter.com/TryBloop)

Cheers!

**Comment by ggordonhall** [comment]
Hey @zawarudo, nice spot! 

We've just set up the bloop community Discord. #216 adds the link to the documentation (https://discord.gg/kZEgj5pyjm). We'll add the link to the website with the next update.

See you on there!
