### ISSUE TITLE
Unable to connect to any github repos

### ISSUE THREAD

**Issue by stefl** [BloopAI/bloop#232]
Hi folks, I installed this a few weeks back, and tried again today with the latest version. I get stuck on the github "select a repo" screen. It looks like it's stuck in a loading state or unable to connect to Github, and the UI is continually is in the flashing loading animation.

There's no way to remove and re-add the Github account, or repair the connection as far as I can see. 

<img width="633" alt="@Stef screenshotted this on 2023-03-04 at 08 14 19@2x" src="https://user-images.githubusercontent.com/132138/222885080-95275719-a419-41a2-89ef-77694833c963.png">

**Comment by ggordonhall** [comment]
Hey @stefl, thanks for raising this. Do you experience the same behaviour on the latest release? https://github.com/BloopAI/bloop/releases/tag/v0.3.0

**Comment by ggordonhall** [comment]
Our latest release ([v0.3.1](https://github.com/BloopAI/bloop/releases)) include a fix for an issue looks like yours, where the initial request for GitHub repos would hang indefinitely (see https://github.com/BloopAI/bloop/pull/281).
