### ISSUE TITLE
[Question] can't install app in mac os Intel

### ISSUE THREAD

**Issue by hehehai** [BloopAI/bloop#268]
**Describe the bug**
1. download the `bloop_0.3.0_aarch64.dmg` from https://github.com/BloopAI/bloop/releases
2. install （no error）
<img width="772" alt="image" src="https://user-images.githubusercontent.com/12692552/226075033-ab3eb1b2-5116-4e0c-a7ee-de510636a96f.png">
<img width="205" alt="image" src="https://user-images.githubusercontent.com/12692552/226075096-d944b40f-ba5d-4f55-a9aa-fc2acc9c248d.png">

3. open app
<img width="372" alt="image" src="https://user-images.githubusercontent.com/12692552/226075107-2f6414d5-f01d-4c34-938a-852ceb3cd655.png">

**Expected behavior**
What did you expect to happen?

**To Reproduce**
mac os 
- Intel Core i9
- 8 Core
- 32 GB 2667 MHz DDR4
- os 13.0.1

**Screenshots or output**
If applicable, add screenshots to help illustrate the bug.

**Additional context**

**Comment by kotAPI** [comment]
Same here, any solutions for intel macbook pro 19?

**Comment by abcwyc** [comment]
same to me

**Comment by peteisacat** [comment]
same here

**Comment by alexcdever** [comment]
this is for the arm CPU, not for the x86 CPU,  you need to build from the source

**Comment by hehehai** [comment]
> this is for the arm CPU, not for the x86 CPU, you need to build from the source

so why not release `x86_64-apple-darwin` ? 😅

**Comment by PandaTwo** [comment]
same same.

**Comment by alexcdever** [comment]
No idea, I'm not a member of this project

**Comment by ggordonhall** [comment]
@hehehai, thanks for your interest in the project!

To confirm, at the moment the only build available is for `aarch64-apple-darwin`. We'll be releasing builds for `x86_64-apple-darwin` (and Windows and Linux) soon.

**Comment by hanxuanliang** [comment]
Can release a version related to Intel in the near future?
I can't wait to use such a badass product.

**Comment by ggordonhall** [comment]
@hehehai The latest bloop release ([v0.3.1)](https://github.com/BloopAI/bloop/releases/tag/v0.3.1) supports `x86_64-apple-darwin`! Follow the link to download `bloop_0.3.1_x64.dmg` on this page: https://github.com/BloopAI/bloop/releases/tag/v0.3.1

Note that because of one of our dependencies - Qdrant - this build will only work on _macOS 12+_.
