### ISSUE TITLE
Use remote services without GitHub?

### ISSUE THREAD

**Issue by nelsonjchen** [BloopAI/bloop#286]
Is it possible to use the remote GPT stuff without granting any GitHub access and only access to local repositories?

**Comment by nelsonjchen** [comment]
https://news.ycombinator.com/item?id=35245166

If that's true, please note that the GitHub credentials effectively stay local and aren't stored by bloop.

**Comment by ggordonhall** [comment]
Hey @nelsonjchen. It's not possible to use GPT without signing in with GitHub. Yes, can confirm that we use GitHub's OAuth device flow, so credentials are stored on your local machine.
