### ISSUE TITLE
Option to fill in own OpenAI key

### ISSUE THREAD

**Issue by nelsonjchen** [BloopAI/bloop#287]
It would be nice to have an option to replace the built-in key with our own OpenAI key. This is obviously not free for the user but it would be an optional hedge against OpenAI making it possible to see queries against a key such as one run by an external party and for those not wanting that code accessible to bloop's key.

e.g. https://news.ycombinator.com/item?id=35237458

**Comment by ggordonhall** [comment]
Hey @nelsonjchen,

This is on our roadmap. We'll support this by open-sourcing the proxy server that LLM calls are routed through. You'll be able to set a custom key there.

There won't be any changes to this repo, so closing this issue.

**Comment by AndryHTC** [comment]
@ggordonhall any news about this?
