### ISSUE TITLE
Repo indexed. Only answers with "Sorry, something went wrong"

### ISSUE THREAD

**Issue by voidxd** [BloopAI/bloop#290]
Hi, thanks for the great software. I'm really excited to use it but I'm running into an issue.

**Describe the bug**
All responses are "Sorry, something went wrong"

**To Reproduce**
- Install Bloop on Windows 10
- Connect your Github
- Fork https://github.com/lirantal/daloradius
- Wait for it to index and then ask any question

**Screenshots or output**
![image](https://user-images.githubusercontent.com/58847957/226506222-7cd4088c-9021-4289-a2dd-2b931deeaf23.png)

Let me know if there's any other info you may need?
Thank you!

**Comment by ggordonhall** [comment]
Hey @voidxd,

Can you try deleting your index and re-indexing? You can delete the bloop cache (which on Windows is in `%LOCALAPPDATA%\ai.bloop.bloop`).
