### ISSUE TITLE
0.3.1 not working in Mac Catalina 10.15.7

### ISSUE THREAD

**Issue by Shomvel** [BloopAI/bloop#291]
**Describe the bug**
I try to install 0.3.1 on my mac. It is unresponsive and can't show me a window. 

**Expected behavior**
The app opens and shows me a window.

**To Reproduce**
Mac Intel
macOS Catalina 10.15.7
1. Download [bloop_0.3.1_x64.dmg](https://github.com/BloopAI/bloop/releases/download/v0.3.1/bloop_0.3.1_x64.dmg)
2. Drag the app to the Applications folder and Open the app with spotlight search.

**Screenshots or output**
<img width="269" alt="image" src="https://user-images.githubusercontent.com/7360051/226506309-c9145c25-c4bf-4cf7-93ae-d7647e9179d7.png">

**Additional context**
None.

**Comment by ananis25** [comment]
Same error. The application icon bounces for a bit in the dock, and then just vanishes. 

MacOS Big Sur (11.4)
Macbook Air (M1, 2020)

**Comment by ggordonhall** [comment]
Hi @Shomvel, bloop is only compatible with MacOS 12+. This is because one of bloop's dependencies - Qdrant - is dependent on MacOS 12+.

**Comment by Shomvel** [comment]
> Hi @Shomvel, bloop is only compatible with MacOS 12+. This is because one of bloop's dependencies - Qdrant - is dependent on MacOS 12+.

Maybe you should be clear about this :/ Cross out app icon if it's detected that macOS version is incompatible, or specify it in the doc. Is supporting FAISS or HNSW feasible btw?  
![image](https://user-images.githubusercontent.com/7360051/226610674-fab5fe9e-926e-4cc2-9e17-69c988f18de4.png)

**Comment by rsdy** [comment]
It is unlikely we'll support macOS versions older than 11, but 0.3.2 will support macOS 11.

**Comment by kroggen** [comment]
@rsdy you said that 0.3.2 will support macOS 11, but the release page has download for macOS 12+
