### ISSUE TITLE
Trying to input before any synched repos - Modal UI problem

### ISSUE THREAD

**Issue by nike1v** [BloopAI/bloop#292]
**Describe the bug**
Install app on windows machine, add GitHub account and click on a text input field before any repos are synchronized.

**Expected behavior**
Loaded image (probably the logo) with less transparent background color.

**To Reproduce**
System - Windows 11

Fresh install the application. -> auth into GitHub -> choose repos to sync -> before any of them are synched, click on the input field -> modal appears to say that I need to wait at least one repo to be synchronized

**Screenshots or output**
If applicable, add screenshots to help illustrate the bug.
![image](https://user-images.githubusercontent.com/20584538/226506601-3c6a0181-9908-4d64-9351-8b647fffd2c3.png)

**Additional context**

**Comment by anastasiya1155** [comment]
Thanks for the report, it will be fixed in the next release
