### ISSUE TITLE
Install on Windows without admin rights

### ISSUE THREAD

**Issue by bambax** [BloopAI/bloop#295]
**What's the problem?**
The .msi installer asks for admin privileges to install the software.

**What's the solution?**
In the enterprise it's very common that machines do not have admin rights. It would be good if it were possible to install without admin rights, or run without installation (by downloading an archive for example, and running from a user directory).

**Comment by delicacyyy** [comment]
![image](https://user-images.githubusercontent.com/11476249/226810168-e57fb0be-71ed-4a86-98db-1cb37dacd7e8.png) SOMEBODY HELP!

**Comment by rsdy** [comment]
@delicacyyy we have a fairly manual process for building on windows right now. Unfortunately until we can roll these out you're best off using our pre-built binaries.

**Comment by delicacyyy** [comment]
> @delicacyyy we have a fairly manual process for building on windows right now. Unfortunately until we can roll these out you're best off using our pre-built binaries.

A little post about steps you taken? Every single bit count ❤️

**Comment by ggordonhall** [comment]
We've added a custom NSIS installer, https://github.com/BloopAI/bloop/pull/1125, so you should now be able to install bloop without admin rights.
