### ISSUE TITLE
Feature Request: Log Out

### ISSUE THREAD

**Issue by kryptoklob** [BloopAI/bloop#297]
Currently cannot log out of the desktop build (I'm on windows).
Perhaps also a button to delete all local/config data so that you can essentially start fresh would be great too!

**Comment by kryptoklob** [comment]
Ah. Gotcha. I'll do this - though I still strongly suggest keeping the "logout" button visible at all times, maybe greyed out (with an explanation) if there's something blocking.

Though I'm not sure why this can't be an "opt-out-and-log-out" button in one go, either?

**Comment by anastasiya1155** [comment]
@kryptoklob you are right, will add this to the next release
