### ISSUE TITLE
Setup Bloop does not accept email addresses with .computer domain

### ISSUE THREAD

**Issue by b5** [BloopAI/bloop#298]
**Describe the bug**
A clear and concise description of what the bug is. If appropriate add a `frontend` or `backend` label.
Basically:
<img width="1312" alt="Screen Shot 2023-03-21 at 10 05 18 AM" src="https://user-images.githubusercontent.com/1154390/226631103-8daeb5a6-1457-42c7-b522-fb05e61eb6a9.png">

**Expected behavior**
What did you expect to happen?
`.computer` is a valid top-level domain 😄. My email should work here.

**To Reproduce**
How can we reproduce the bug? Helpful information could include:
- Details about your system
- The data that you had indexed
- The query that you ran

**Screenshots or output**
If applicable, add screenshots to help illustrate the bug.

**Additional context**
App looks really slick. Great stuff!

**Comment by anastasiya1155** [comment]
Thanks for the report, it will be fixed in the next release
