### ISSUE TITLE
Unable to sync... anything

### ISSUE THREAD

**Issue by igorgue** [BloopAI/bloop#300]
Hi,

I'm on Linux and I cannot sync anything...

Is there uninstall docs, I wanna try again but clearing the db you guys probably made in my machine.

**Comment by ggordonhall** [comment]
Hey @igorgue. Can you try clearing these:
```
~/.cache/bloop
~/.cache/ai.bloop.bloop
~/.local/share/ai.bloop.bloop
```

Good shout on uninstall docs. I'll add some - we currently don't have any.

**Comment by austinmw** [comment]
@ggordonhall Clearing those cache paths didn't work for me (mac).

**Comment by rsdy** [comment]
@austinmw On mac the correct path is `~/Library/Caches/ai.bloop.bloop`.
