### ISSUE TITLE
bug: The interface shows an error

### ISSUE THREAD

**Issue by maye174** [BloopAI/bloop#301]
**Describe the bug**
The interface shows an error  
Occurs when clicking the button to the left of the chat box

**Expected behavior**
normal display

**To Reproduce**
- win11 22621.1413
- 
- 

**Screenshots or output**

![屏幕截图 2023-03-22 004856](https://user-images.githubusercontent.com/96584640/226684270-85410c7a-431b-4971-94c8-ecbdb257eaa2.png)

**Additional context**

**Comment by maye174** [comment]
> Do you have at least one repo with status indexed? (should show a green dot and the date of the last sync) If not you should wait for at one repo to finish indexing and try searching after that.

I know, I'm referring to this popup that doesn't display correctly

**Comment by anastasiya1155** [comment]
Fixed by https://github.com/BloopAI/bloop/pull/288
