### ISSUE TITLE
Unable to remove Github repository

### ISSUE THREAD

**Issue by chrisbro** [BloopAI/bloop#311]
**Describe the bug**
I successfully added a private Github repo to Bloop. I then went to remove it in the "Manage Repositories" screen, but clicking the "Remove" button does nothing. Does not remove the repo, does not show any error messages. 

**Expected behavior**
Github repository to be removed from Bloop.

**To Reproduce**
- Bloop version 0.3.1
- M2 Macbook Pro, macOS Ventura 13.2
- Had indexed a local repository, and the Github one that I can't remove.
- Go to the "Manage Repositories" screen
- Click "Remove"
- Observed that nothing happens - the repository remains in Bloop, and no error message is shown.

**Screenshots or output**
If applicable, add screenshots to help illustrate the bug.

**Additional context**
- The Github repository and the local repository that I'm indexing are the same one. In other words, I'm indexing `github.com/foo`, as well as my locally synced copy of `foo`.
- Restart of Bloop did not change behavior.

**Comment by EdAyers** [comment]
I sometimes have to wait about 5 seconds with no visual feedback before the item disappears from the list. Perhaps this is the same bug.

**Comment by anastasiya1155** [comment]
this should be fixed in the next release

**Comment by ramnes** [comment]
Just installed v0.3.2 and while it now removes the repository from the list in "Manage repositories", the repository is still in sync in all other parts of the app.
