### ISSUE TITLE
Default question fails

### ISSUE THREAD

**Issue by ramnes** [BloopAI/bloop#335]
**Describe the bug**
The default "What does this repo do?" question never gives a correct answer. Following questions work as expected.

**Expected behavior**
An answer that's not a "Sorry". :)

**To Reproduce**
- Click on any repo.
- Wait for the answer to the default "What does this repo do?" question.

**Screenshots or output**
<img width="377" alt="image" src="https://user-images.githubusercontent.com/835072/227481845-56db19f8-5847-4496-94ad-9e91e5e4f174.png">

**Additional context**
- Using latest macOS bloop build available (v0.3.1)
- Using both local (2x) and GitHub (1x) repositories.

**Comment by ggordonhall** [comment]
Hey @ramnes, do the repos in question contain any markdown files? The initial search here is constrained to markdown files, and if none are found, we emit this message. If they do contain markdown files can you reproduce the issue on `v0.3.2`?

**Comment by ramnes** [comment]
Yep, it does: https://github.com/ramnes/mongo-thingy

Yes, happens on v0.3.2.

That being said, it might be linked to issue #311, because this is the repository I tried to remove (and that still appears in Bloop).

I may have concluded too early that it happens all the time because I had the same message on another repository that indeed doesn't have any Markdown file. Maybe another question should be asked if no Markdown file exist in the repository. :)

**Comment by hanxuanliang** [comment]
The issue can be reproduced in v0.3.3
- Using latest macOS bloop build available (v0.3.3)

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/29874640/230716056-1a0de022-b2c7-4b11-9166-a26ca2ba66e9.png">

Reproduction steps:
1. Clone https://github.com/centrifugal/centrifuge to local
2. Import
3. Ask this question: What does this repo do? repo:centrifuge lang:markdown

**Comment by rsdy** [comment]
@ramnes @hanxuanliang I managed to reproduce this, but unfortunately not reliably. Deleting my repositories and re-indexing them from the user interface seems to have fixed the issue, though.

We're planning a new release from `main` soon which will fix issues with deleting repositories, so will be easier to pin down what's wrong.

**Comment by ggordonhall** [comment]
This default question has been removed as of v0.4.0: https://github.com/BloopAI/bloop/releases/tag/v0.4.3
