### ISSUE TITLE
0.3.2 release missed windows MSI  file in release artifacts

### ISSUE THREAD

**Issue by Slach** [BloopAI/bloop#338]
Is this final decision to remove windows support?

**Comment by rsdy** [comment]
We're still ironing out the release process, unfortunately we won't be able to get a Windows release out till early next week. Bear with us, and we'll send you an update in this issue!

**Comment by ggordonhall** [comment]
Hey @Slach, v0.3.2 Windows builds have now been uploaded to the release page. https://github.com/BloopAI/bloop/releases/tag/v0.3.2

**Comment by Slach** [comment]
@ggordonhall hm, looks like
https://github.com/BloopAI/bloop/releases/download/v0.3.2/bloop_0.3.2_x86_en-US.msi
this is the same as
https://github.com/BloopAI/bloop/releases/download/v0.3.2/bloop_0.3.2_x64_en-US.msi

files have the same hash, is this expected?
