### ISSUE TITLE
Stuck at "Sync local repositories" when trying to add a large repo

### ISSUE THREAD

**Issue by AllenDang** [BloopAI/bloop#410]
**Describe the bug**
Add a large local repo (unreal engine 5's source code, I know this might be too much for bloop) will stuck in "Sync local repositories" for half an hour...

![截屏2023-04-24 18 08 16](https://user-images.githubusercontent.com/18550/233966786-98df3fe6-3c67-4b21-8af4-7e67aefdcb1b.png)

**Expected behavior**
The repo could be added and indexied.

**Comment by ggordonhall** [comment]
Hi @AllenDang, I'll try and reproduce this.

Can you send me a link to the repo you're trying to index? Are you running v0.3.4? Which platform are you running it on?

**Comment by AllenDang** [comment]
@ggordonhall Yes, I'm running 0.3.4, and my OS is macOS v13.
Here is the repo: https://github.com/EpicGames/UnrealEngine

**Comment by itribs** [comment]
you must use "git clone" to get the project instead of using the "Download ZIP" button on GitHub

**Comment by ggordonhall** [comment]
This should be fixed in `v0.4.*`: https://github.com/BloopAI/bloop/releases/tag/v0.4.3
