### ISSUE TITLE
v0.3.3 Sync local repositories is not working and keeps on loading

### ISSUE THREAD

**Issue by MutahharAllshore** [BloopAI/bloop#425]
**Describe the bug**
On my Windows system, I installed v0.3.3 but unfortunately, the **Sync local repositories** feature is not functioning properly. I have designated the appropriate folder where my git repository is located, however, it continuously displays the loading screen even after waiting for more than an hour (see the screenshot below).

**Expected behavior**
The local repository should sync.

**To Reproduce**
- Downloaded and installed v0.3.3 from [the releases](https://github.com/BloopAI/bloop/releases/download/v0.3.3/bloop_0.3.3_x64_en-US.msi)
- OS version: Windows 11 Enterprise, Version 22H2, OS build 22621.1555
- Tried to sync a local git repository, it continuously displays the loading screen

**Screenshots or output**
![*Sync local repositories screen](https://user-images.githubusercontent.com/129213870/234583087-499e171e-04fc-4ed1-a209-4d1d242f66fa.png)

**Comment by ggordonhall** [comment]
This should be fixed in `v0.4.*`: https://github.com/BloopAI/bloop/releases/tag/v0.4.3

**Comment by MutahharAllshore** [comment]
As this issue has been closed. I've created a new issue for this here #641
