### ISSUE TITLE
get errors when i run bloop_0.3.4_amd64.AppImage in ubuntu 18. Can i run which version?

### ISSUE THREAD

**Issue by WBWhiteBeard** [BloopAI/bloop#428]
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by bloop)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by bloop)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by bloop)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by bloop)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by bloop)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by bloop)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libwebkit2gtk-4.0.so.37)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libwebkit2gtk-4.0.so.37)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libwebkit2gtk-4.0.so.37)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libwebkit2gtk-4.0.so.37)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libwebkit2gtk-4.0.so.37)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgtk-3.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgtk-3.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgdk-3.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libcairo.so.2)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libcairo.so.2)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgio-2.0.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgio-2.0.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgio-2.0.so.0)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libjavascriptcoregtk-4.0.so.18)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libjavascriptcoregtk-4.0.so.18)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libjavascriptcoregtk-4.0.so.18)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libjavascriptcoregtk-4.0.so.18)
bloop: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libjavascriptcoregtk-4.0.so.18)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libglib-2.0.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libglib-2.0.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libglib-2.0.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libglib-2.0.so.0)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libicui18n.so.70)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libicuuc.so.70)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libicuuc.so.70)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libicuuc.so.70)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libsystemd.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libsystemd.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libsystemd.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libsystemd.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libsystemd.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libxml2.so.2)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libxml2.so.2)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libxml2.so.2)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libxml2.so.2)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libsqlite3.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libsqlite3.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libsqlite3.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libsqlite3.so.0)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libxslt.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libxslt.so.1)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/liblcms2.so.2)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgcrypt.so.20)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgstreamer-1.0.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgstreamer-1.0.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgstreamer-1.0.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgstpbutils-1.0.so.0)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgstaudio-1.0.so.0)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgsttag-1.0.so.0)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgstvideo-1.0.so.0)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libpng16.so.16)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libopenjp2.so.7)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libopenjp2.so.7)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libwebp.so.7)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libwebp.so.7)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libenchant-2.so.2)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgmodule-2.0.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libwayland-server.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libwayland-server.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libwayland-server.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libwayland-client.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libepoxy.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libxkbcommon.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libwayland-cursor.so.0)
bloop: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libpixman-1.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libmount.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libmount.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libselinux.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libselinux.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libselinux.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/liblzma.so.5)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/liblzma.so.5)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libcap.so.2)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libunwind.so.8)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libunwind.so.8)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libdw.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libdw.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgudev-1.0.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libpsl.so.5)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libgssapi_krb5.so.2)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libevdev.so.2)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libdbus-1.so.3)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libdbus-1.so.3)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libXau.so.6)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libblkid.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libelf.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libudev.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libudev.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libudev.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libudev.so.1)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libunistring.so.2)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libunistring.so.2)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libkrb5.so.3)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libkrb5.so.3)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libk5crypto.so.3)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libkrb5support.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libkrb5support.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libbsd.so.0)
bloop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bloop_tyvRnA/usr/lib/libmd.so.0)

**Comment by rsdy** [comment]
Unfortunately we will not be able to focus on old LTS versions like this. Please upgrade to the latest LTS to run Bloop.
