### ISSUE TITLE
How to remove this app and cached file?

### ISSUE THREAD

**Issue by BreakLimiter** [BloopAI/bloop#492]
something strucked, and i want to clean the cache and reinstall it. here's the two data dirs i found, is there other dirs?

```bash
$HOME/Library/Saved Application State/ai.bloop.bloop.savedState
$HOME/Library/Caches/ai.bloop.bloop
```

**Comment by rsdy** [comment]
For macOS, there's also a WebKit cache at `$HOME/Library/WebKit/bloop/`, but generally speaking deleting the Cache dir will be sufficient for a complete reset of the application state.

**Comment by blowpai** [comment]
@rsdy Looks like : `$HOME/Library/WebKit/ai.bloop.bloop` right?

**Comment by rsdy** [comment]
That should be correct, yes.
