### ISSUE TITLE
[bug] wrong wording for no repo

### ISSUE THREAD

**Issue by kuriemit** [BloopAI/bloop#495]
![image](https://github.com/BloopAI/bloop/assets/133642542/59aada5d-70ff-4996-91b6-fa7aa976f647)

Acutally my GitHub account is connected, but no repo is indexed. It told me to "Connect GitHub", but it's already connected.

**Comment by ggordonhall** [comment]
Can you provide a bit more information about the version of bloop you are running, and the platform that you are running it on?

What happens if you 'Connect GitHub'?
