### ISSUE TITLE
Bloop 0.3.4 seems to reference different line numbers in explanations of code than what it is calling a line number in its preview?

### ISSUE THREAD

**Issue by jelber2** [BloopAI/bloop#496]
**Describe the bug**
bloop 0.3.4 (Deb file on Ubuntu Cinnamon 23.04 x86_64) seems have a strange notion of what line number are associated with the line numbers in its preview versus the line numbers it references in 

**Expected behavior**
If one asks, ```can you explain line number 23 repo:REPONAME lang:C```, bloop should actually report an explanation of that line at least based on its preview?

**Comment by ggordonhall** [comment]
Hey @jelber2, in v0.3.4 we're not passing line numbers to the LLM so it won't be able to answer questions that refer to code by line numbers/ranges. In the coming update we're changing this and feeding in line ranges too, but even then it's still sometimes tricky to get the LLM to reason about them!
