### ISSUE TITLE
0.4. 0 Not available on windows

### ISSUE THREAD

**Issue by Dcr-chen** [BloopAI/bloop#571]
Version 0.4. 0 can't be logged in on windows. The specific situation is that when I click connect account, the page I jump to doesn't show the verification code, and I click the github authentication button, but then I open windows explorer

**Comment by Slach** [comment]
https://github.com/BloopAI/bloop/releases/tag/v0.4.1

**Comment by ggordonhall** [comment]
v0.4.3 Windows release: https://github.com/BloopAI/bloop/releases/tag/v0.4.3
