### ISSUE TITLE
[question] what means Remote removed status for public github repository?

### ISSUE THREAD

**Issue by Slach** [BloopAI/bloop#603]
I install bloop 0.4.1 from scratch in Windows and tried add https://github.com/ClickHouse/ClickHouse/ as public repository
and got following picture
![image](https://github.com/BloopAI/bloop/assets/105560/0fe9fd17-2521-4761-85a1-88a9b1ee9b2b)

what mean `Remote removed` status?

**Comment by rsdy** [comment]
@Slach Instead of using `https://github.com/X/Y`, please enter just `X/Y`, and it should work. This will be fixed in the next release.
