### ISSUE TITLE
Version 0.4. 3 issues

### ISSUE THREAD

**Issue by Dcr-chen** [BloopAI/bloop#616]
Since the revision, to the 0.4. 3 version, has been not as good as the old version, often can not search, prompted encountered some errors, but the same problem. On the 0.3. 4 version, you can search normally. Very distressed

**Comment by ggordonhall** [comment]
Hey @Dcr-chen, we're working hard to reduce the error rate. Upgrading to v0.4.4 should result in more stable output.

**Comment by Dcr-chen** [comment]
OK~ I was updated
