### ISSUE TITLE
Github login requests permissions for all repos, no option to select

### ISSUE THREAD

**Issue by bhaktatejas922** [BloopAI/bloop#626]
Github login requests permissions for all repos, no option to select as the dmg login setup page says.

**Comment by rsdy** [comment]
This is unfortunately a limitation of GitHub's OAuth permission model. You are always able to limit permissions based on organizations, though.

After logging in with GitHub, bloop will only interact with repositories you select.

**Comment by bhaktatejas922** [comment]
I don't believe this is true, if you look at how netlify does Github login, you're able to select specific repos and it only have access to those

**Comment by rsdy** [comment]
Netlify uses Github's App permission model, which stores your credentials on their servers.

With the open source Bloop app you are in control of your credentials to Github. We never store them on our servers, and what the app does with your credentials is completely transparent.

If you are happy to try Bloop in the browser, our SaaS offering uses the same permissions model that Netlify uses, and gives you fine-grained permissions.
