### ISSUE TITLE
Allow use of Azure OpenAI API Keys (Azure Cognitive Service API)

### ISSUE THREAD

**Issue by mrjk05** [BloopAI/bloop#630]
**What's the problem?**
Being able to utilise Azure Open AI API keys ( Cognitive Service API) (not to get confused with OpenAI API Keys). Azure OpenAI is its own billed service on Azure. This is good for businesses and teams who utilise OpenAI via Azure to power their own internal LLM. 

**What's the solution?**
Set up connectivity to Azure OpenAI AI (Cognitive Service API)

**Additional context**
Azure Cognitive Serivces Documentation: https://learn.microsoft.com/en-AU/azure/cognitive-services/

**Comment by ggordonhall** [comment]
Hi @mrjk05, we do use Azure OpenAI to on our LLM backend.

**Comment by recursionbane** [comment]
@ggordonhall, where can I find instructions on using Azure OpenAI for the locally run version of bloop?
