### ISSUE TITLE
Support for multiple git repositories (treated as a single one)

### ISSUE THREAD

**Issue by cryptosebek** [BloopAI/bloop#640]
There's the case when there's a multiple repositories within a single folder. Would be cool to have an ability to scan folder recursively for all the git repositories in it to be able to query it as a single codebase.

Example folder structure:
-MyProjectRootFolder:
--some shared library code repo
--service 1 repo
--service 2 repo
----sub-service repo
etc.

I am assuming that this would be easier to implement rather than not relaying to git repositories at all, which actually could be even cooler.

**Comment by ggordonhall** [comment]
Hey @cryptosebek,

Cross-repo search is on our roadmap and should give you the same experience. You'll be able to get bloop to answer with respect to several repositories at once (which you can select).
