### ISSUE TITLE
**Sync local repositories** is doing nothing on Windows in Version 0.4.4. 

### ISSUE THREAD

**Issue by MutahharAllshore** [BloopAI/bloop#641]
**Describe the bug**
I have recently installed version 0.4.4 of the GitHub software, but I am encountering a persistent issue. When attempting to sync a folder using the "Sync local repositories" feature, the process fails to initiate and remains unresponsive.

**Expected behavior**
It should show me the list of repositories to index.

**To Reproduce**
How can we reproduce the bug? Helpful information could include:
1. Install `bloop` version [0.4.4](https://github.com/BloopAI/bloop/releases/download/v0.4.4/bloop_0.4.4_x64_en-US.msi).
2. Launch the Bloop application on the local machine.
3. Navigate to the "Sync local repositories" feature.
4. Select a folder to sync.
5. The popup remains open and do nothing.

**Screenshots or output**
https://github.com/BloopAI/bloop/assets/129213870/00798bf8-0994-415b-87df-a05b2a2498f2

**Comment by Ceasy** [comment]
I have exactly the same problem.

**Comment by arthur-x88** [comment]
Same here

**Comment by ggordonhall** [comment]
Thanks for reporting this. Does this problem persist on the latest version of bloop? Also, which platform do you experience this issue on?

**Comment by MutahharAllshore** [comment]
@ggordonhall 
> **Does this problem persist on the latest version of bloop?**

I've not tested with the latest version ([v0.4.8](https://github.com/BloopAI/bloop/releases/tag/v0.4.8)). I will test wit the latest version and will update it here.

---

> **Also, which platform do you experience this issue on**

I am using Windows 11.

**Comment by MutahharAllshore** [comment]
@ggordonhall I tried [v0.4.7](https://github.com/BloopAI/bloop/releases/tag/v0.4.7) because [v0.4.8](https://github.com/BloopAI/bloop/releases/tag/v0.4.8) does not have a Windows build yet, and the problem still exists.

**Comment by ggordonhall** [comment]
@MutahharAllshore There is a Windows build for v0.4.13. Can you reproduce the issue?

**Comment by VitorCaleffi** [comment]
Can confirm the issue still happens for v0.4.13 (Windows 11)

**Comment by RickyGrassmuck** [comment]
Was just about to hop in to confirm that v0.4.13 on Windows 11 was still not functional when trying to select a local repository.

I initially attempted to load a local repo after installing/launching for the first time which resulted in the reported behavior but after that failed, I went and added some repo's directly from Github which all worked as expected. Apparently adding the repos through Github changed something internally as I was able to successfully add a local repository after those github repos were added.

I just did a quick test and deleted all the repos I had synced and retried adding the local repo again and it was able to load just fine.

Seems like something is holding it up when trying to add a local repository as the very first repo but for some reason adding from another source first clears up this hurdle and allows for local repos to be added.

Not sure if it's related but I did notice that for some reason after adding the local repo successfully, all my other repo's were queued up for indexing again even though nothing had changed with them.

Hope this helps tracking down the culprit. I'm new to the project and haven't really gotten to poke around but if it helps I'm happy to send some logs.

**Comment by MutahharAllshore** [comment]
@ggordonhall, I just tested with [v0.4.17](https://github.com/BloopAI/bloop/releases/tag/v0.4.17) and the issue is still there.

**Comment by MutahharAllshore** [comment]
@ggordonhall
Yes, in the main directory that I am selecting in the bloop to load, I have multiple directories with a **.git** folder in them.

**Comment by ggordonhall** [comment]
Does this happen when you select another directory, one that has fewer levels of nesting? Scanning for local repos could take a long time if you select a directory with a massive number of nested files.

**Comment by MutahharAllshore** [comment]
To provide some more context. I have installed **Xampp** on Windows. And I select the **htdocs** directory in the bloop to load. And in the **htdocs** directory I've at least 3 directories that have a **.git** directory in them.

**Comment by MutahharAllshore** [comment]
> Does this happen when you select another directory, one that has fewer levels of nesting? Scanning for local repos could take a long time if you select a directory with a massive number of nested files.

@ggordonhall 
The directory I am selecting has a single level of nesting.

**Comment by ggordonhall** [comment]
How many files are in this directory? Do you experience the same issue with every dir you try or only this one?

**Comment by MutahharAllshore** [comment]
@ggordonhall 
I checked recursively and the directory has **76681** files.
