### ISSUE TITLE
Support for Azure Devops

### ISSUE THREAD

**Issue by chaoscreater** [BloopAI/bloop#697]
Hi there,

Does this currently only support Github repo? Is it possible for this to support Azure Devops please

**Comment by ggordonhall** [comment]
We currently only support GitHub remotes (support for more is on our roadmap). However you can use bloop with any Git repo if you first clone it to your machine and sync it as a 'local' repo:

<img width="385" alt="Screenshot 2023-07-12 at 10 04 21" src="https://github.com/BloopAI/bloop/assets/24595376/f857b6e7-29f3-42f4-a09e-e09d201d1b58">
