### ISSUE TITLE
SCAM

### ISSUE THREAD

**Issue by Iamtheoldman** [BloopAI/bloop#803]
Went and signed up for there trial and the whole website is a joke they will take your money and not let you cancel https://www.loom.com/share/48f5919e9f4344c7be5500dfbb8e3246?sid=1ff239ee-d3e4-4847-bcc3-3bb6765f233f

**Comment by ggordonhall** [comment]
Hi @Iamtheoldman. I'm sorry to see that you've had an issue getting set up on Cloud. We'd love to help you get bloop up and running smoothly.

A couple of things to note:

- We do not charge until the end of the 7 day trial period
- If you'd like to cancel just get in touch at contact@bloop.ai

We're a small startup working hard to build a great product - we try to fix bugs like this as soon as we're alerted to them!

**Comment by Iamtheoldman** [comment]
I emailed the contact, thank you. when can i expect a follow up?
