### ISSUE TITLE
Add Spanish Language Support to Bloop

### ISSUE THREAD

**Issue by Saul-BT** [BloopAI/bloop#817]
Hello,

As a frequent user of this application and a native Spanish speaker, I have noticed that Bloop currently only supports English and Japanese languages. Considering the large number of potential users who are proficient in or prefer using Spanish, I believe it would be a beneficial extension to the application's functionality to add Spanish language support.

Details of the proposed enhancement are as follows:
## Feature description:

1. Add support for Spanish language interface.
2. Ensure that all interactive controls, menu items, error messages, and information texts are translated appropriately.
3. Offer a smooth transition between the different language settings within the application's settings interface.

## Benefit:

By adding Spanish language support, Bloop will become more accessible to a wider audience, potentially increasing its user base and user satisfaction.

I would be happy to contribute to developing this feature if needed.

Looking forward to your feedback.

### Credits:

To @BB-fat for his great writing in issue #815, this one is highly inspired by it.

**Comment by anastasiya1155** [comment]
Hello! Thanks for this feature request. I have opened a PR to add Spanish localization, but nobody on our team speaks Spanish and we need your help to verify the translations. Please check this PR out #822

**Comment by Saul-BT** [comment]
I can help with that :)
