### ISSUE TITLE
v0.4.11 crash on windows

### ISSUE THREAD

**Issue by boquanzhou** [BloopAI/bloop#818]
**Describe the bug**
When I first launch Bloop after installation, it crashes.

**Expected behavior**
What did you expect to happen?

**To Reproduce**
1. Install the v0.4.11 on windows.
2. launch Bloop.

**Screenshots or output**

**Additional context**

**Comment by ggordonhall** [comment]
Thanks for the report @boquanzhou, we're investigating this.

**Comment by accordaccount** [comment]
It does the same with 0.4.12. Is that expected?

**Comment by accordaccount** [comment]
I can confirm that 0.4.13 now works on Windows. (I'm using Win11)
Thanks for the hard work, you are awesome!

**Comment by calyptobai** [comment]
This should be fixed in `0.4.13`, thanks for reporting the issue!
