### ISSUE TITLE
Evaluate Profile-Guided Optimization (PGO)

### ISSUE THREAD

**Issue by zamazan4ik** [BloopAI/bloop#898]
**What's the problem?**
It's not a problem. It's an idea of how to (possibly) improve Bloop's performance.

**What's the solution?**
Recently I did many PGO benchmarks on multiple projects - the results are available [here](https://github.com/zamazan4ik/awesome-pgo). There you can find many possibly related to Bloop applications. E.g. I have PGO [results](https://github.com/quickwit-oss/tantivy/issues/2163) for Tantivy, which is used by Bloop.

We need to evaluate PGO applicability to Bloop (the `bleep` part, I guess). And if it helps to achieve better performance - add a note to the documentation about that. In this case, users and maintainers will be aware of another optimization opportunity for Bloop. Also, PGO integration into the build scripts can help users and maintainers easily apply PGO for their own workloads.

After PGO, I can suggest evaluating [LLVM BOLT](https://github.com/llvm/llvm-project/blob/main/bolt/README.md) as an additional optimization step after PGO.

For the Rust projects, I recommend starting with [cargo-pgo](https://github.com/Kobzol/cargo-pgo) - it makes easier PGO optimization in many cases.

**Comment by ggordonhall** [comment]
Hi @zamazan4ik. While this sort of optimisation might help improve bloop's performance, our largest bottlenecks are generating embeddings when indexing and calling OpenAI GPT when querying. At the moment we're focussing on these!
