### ISSUE TITLE
Can't log in to bloop.ai: Github authentication opens a file browser.

### ISSUE THREAD

**Issue by ckemmler** [BloopAI/bloop#902]
**Describe the bug**
I have linked my Github account, then I quit the app. Now I can't log in to bloop.ai, because Github authentication opens a file browser. After that, I'm stuck in the Setup bloop screen with the Github widget displauing "Waiting for authentication..."

**Expected behavior**
I would expect to still be authenticated, or at least to be able to easily log in again.

**To Reproduce**
How can we reproduce the bug? Helpful information could include:
- Details about your system
MacBook Pro M1 – Ventura 13.4.1 (c) 

- The data that you had indexed
A few local repositories

- The query that you ran
none

**Screenshots or output**
If applicable, add screenshots to help illustrate the bug.

**Additional context**

**Comment by ckemmler** [comment]
I just checked:

-   launch bloop -> qdrant process is there
    

-   quit bloop -> qdrant process disappears

so no :-(


------- Original Message -------
Le mercredi 30 août 2023 à 10:09, rsdy ***@***.***> a écrit :

**Comment by rsdy** [comment]
Just to confirm, what is the bloop version you're running?

**Comment by ckemmler** [comment]
Version 0.4.15 (20230828.120352)


------- Original Message -------
Le mercredi 30 août 2023 à 10:24, rsdy ***@***.***> a écrit :

**Comment by ggordonhall** [comment]
This should be fixed in 0.4.16: https://github.com/BloopAI/bloop/releases
