### ISSUE TITLE
4.15 & 4.16 do not start correctly, bloop unusable on Win 11

### ISSUE THREAD

**Issue by justinwj** [BloopAI/bloop#917]
**Describe the bug**
4.15 & 4.16 bloop do not allow sign in or to be used at all. 4.13 was working, i added 17 repositories. it stopped working. it seems like when uninstalling bloop something is left behind so bloop will not start properly ever on. all versions from 4.9 onward are not working on my win11pro computer

**Expected behavior**
bloop should install and start and be usable and be uninstallible and reinstallible without any problems

**To Reproduce**
just try to use bloop on win 11 pro.
      **my computer specs:**
Processor	13th Gen Intel(R) Core(TM) i9-13900K   3.00 GHz
Installed RAM	64.0 GB (63.8 GB usable)
System type	64-bit operating system, x64-based processor
      **my Windows specs**
Edition	Windows 11 Pro
Version	22H2
Installed on	‎5/‎8/‎2022
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

**Screenshots or output**
below is 4.15 bloop running but bloop app does not allow sign in, sign in loads File Explorer instead
![Screenshot 2023-08-31 165219](https://github.com/BloopAI/bloop/assets/78885595/27edd54e-d329-4837-bddc-220559d108e8)
below is picture of 4.16 startup window, this is as far as bloop will ever go on my win11pro computer
![Screenshot 2023-08-31 173624](https://github.com/BloopAI/bloop/assets/78885595/0018bdb2-df1e-4571-b60a-d034e5e23375)

**Comment by ggordonhall** [comment]
Hi @justinwj, this is a known bug, related to the time it takes to start up Qdrant. We're testing a fix for this https://github.com/BloopAI/bloop/pull/887 and will release a patch as soon as possible.

**Comment by aliffatulmf** [comment]
> Having the same issue. Tried updating to version 5 and it's still not working.

try to uninstall, then delete all 'bloop' folders in AppData, and try installing the latest version.

**Comment by ggordonhall** [comment]
Did deleting `%APPDATA%/bloop` work for you @gldstrrbt?

**Comment by justinwj** [comment]
it did not, i have stopped trying to use Bloop for the time being.



Sent using {0}








---- On Wed, 20 Sep 2023 10:45:56 -0700 Gabriel Gordon-Hall ***@***.***> wrote ---





Did deleting %APPDATA%/bloop work for you https://github.com/gldstrrbt?

**Comment by ggordonhall** [comment]
Closing this thread in favour of https://github.com/BloopAI/bloop/issues/1035
