### ISSUE TITLE
The v0.4.16 in windows cannot answer any query

### ISSUE THREAD

**Issue by boquanzhou** [BloopAI/bloop#927]
**Describe the bug**
I downloaded the latest version on windows and found that whatever query I input, it reponded me with something went wrong

**Expected behavior**
What did you expect to happen?

**To Reproduce**
How can we reproduce the bug? Helpful information could include:
- Details about your system
- The data that you had indexed
- The query that you ran

**Screenshots or output**
If applicable, add screenshots to help illustrate the bug.

**Additional context**

**Comment by ggordonhall** [comment]
Can you provide some more information about the version of bloop that you're using, your operating system, the repos you have indexed, and the types of queries that you have inputted?
