### ISSUE TITLE
#v0.4.17，#win10，can not get into the application

### ISSUE THREAD

**Issue by Haoyu2405** [BloopAI/bloop#939]
# In the Windows 10 system, when I double-click on the icon and stay on this interface.
# What should I do to solve this problem?
![image](https://github.com/BloopAI/bloop/assets/84794739/6c251826-1c09-45fc-9166-3be9985ae2e1)

**Comment by Haoyu2405** [comment]
I tried uninstalling and reinstalling, but it still didn't work.

**Comment by CAN1177** [comment]
#v0.4.17，#mac intel，I also encountered this problem

**Comment by ggordonhall** [comment]
Closing this as it is a duplicate of https://github.com/BloopAI/bloop/issues/917
