### ISSUE TITLE
The app hangs on "loading..." after upgrading from version 0.4.? to 0.5.2

### ISSUE THREAD

**Issue by ckemmler** [BloopAI/bloop#976]
**Describe the bug**
The app hangs on "loading..." after upgrading from version 0.4.? to 0.5.2

**Expected behavior**
I expected the app to just launch normally

**To Reproduce**
I'm on a Macbook Pro M1, Ventura

**Screenshots or output**
<img width="498" alt="image" src="https://github.com/BloopAI/bloop/assets/41804/76877cf8-4a22-4dfc-98fb-1a2b1e3b1688">

**Comment by ggordonhall** [comment]
Thanks for reporting this. To help debug can you confirm a couple of things:
- With bloop closed, do you have a Qdrant process running on port 6333? `lsof -i :6333`
- How large is your bloop index directory? `du -sh ~/Library/Application\ Support/ai.bloop.bloop`

Deleting your index directory and restarting the app may resolve this.

**Comment by ckemmler** [comment]
Yes there is a qdrant process running on port 6333 (what is it?)
My bloop index directory is 283M

Deleting the index directory didn't solve the issue
killing qdrant did.

Thanks!
